# Generated by Django 4.1.3 on 2023-01-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
